#!/usr/bin/env python3
"""Build the tracked, static ConPath research demo from an experiment report.

The website intentionally consumes a compact snapshot rather than loading files from ``results/``
at runtime.  ``results/`` is ignored because it contains large/reproducible experiment outputs;
the small snapshot under ``site/data`` is the reviewable hand-off that travels with the repository.
"""

from __future__ import annotations

import argparse
from datetime import datetime, timezone
from html import escape
import json
import math
from pathlib import Path
import shutil
from typing import Any


PROJECT_ROOT = Path(__file__).resolve().parents[1]
DEFAULT_REAL_REPORT = PROJECT_ROOT / "results" / "tum_rgbd_freiburg1_desk_pilot" / "report.json"
DEFAULT_FLATLANDS_REPORT = (
    PROJECT_ROOT / "results" / "p1_flatlands_query_audit_bounded" / "report.json"
)
DEFAULT_FLATLANDS_PROVENANCE_REPORT = (
    PROJECT_ROOT / "results" / "p1_flatlands_provenance_manifest" / "report.json"
)
DEFAULT_FLATLANDS_BASELINE_ROOT = PROJECT_ROOT / "results"

FRIENDLY_NAMES = {
    "constant_query_radius": "Constant query-radius prior",
    "independent_bernoulli": "Independent cell completion",
    "direct_query_mlp": "Direct query predictor",
    "edge_connectivity_calibrated": "Edge-connectivity calibrated",
    "random_completion": "Uniform unknown completion",
    "deterministic_threshold": "Deterministic threshold",
    "correlated_decoder_no_reachability": "Correlated decoder (no reachability)",
    "PathRel_correlated_event": "ConPath correlated event (oracle proxy)",
}


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument(
        "--report",
        type=Path,
        default=PROJECT_ROOT / "results" / "p0_death_test" / "report.json",
        help="P0 report generated by scripts/evaluate_p0.py",
    )
    parser.add_argument(
        "--output-dir",
        type=Path,
        default=PROJECT_ROOT / "site",
        help="tracked static site directory",
    )
    parser.add_argument(
        "--real-report",
        type=Path,
        default=DEFAULT_REAL_REPORT,
        help="real-data pilot report generated by scripts/run_tum_rgbd_pilot.py",
    )
    parser.add_argument(
        "--skip-real",
        action="store_true",
        help="only rebuild the legacy synthetic P0 snapshot (development use)",
    )
    parser.add_argument(
        "--flatlands-report",
        type=Path,
        default=DEFAULT_FLATLANDS_REPORT,
        help="bounded FlatLands natural-query audit report",
    )
    parser.add_argument(
        "--flatlands-provenance-report",
        type=Path,
        default=DEFAULT_FLATLANDS_PROVENANCE_REPORT,
        help="FlatLands archive/provenance audit report",
    )
    parser.add_argument(
        "--skip-flatlands",
        action="store_true",
        help="do not rebuild the public FlatLands data-audit snapshot",
    )
    parser.add_argument(
        "--flatlands-baseline-root",
        type=Path,
        default=DEFAULT_FLATLANDS_BASELINE_ROOT,
        help="results root containing the validation-only P1 baseline reports",
    )
    parser.add_argument(
        "--skip-flatlands-baselines",
        action="store_true",
        help="do not rebuild the validation-only FlatLands baseline snapshot",
    )
    parser.add_argument(
        "--include-legacy",
        action="store_true",
        help="also copy legacy synthetic P0 assets (never used by the public page)",
    )
    return parser.parse_args()


def json_safe(value: Any) -> Any:
    """Convert NumPy-style non-finite values into strict JSON ``null`` values."""

    if isinstance(value, dict):
        return {str(key): json_safe(item) for key, item in value.items()}
    if isinstance(value, (list, tuple)):
        return [json_safe(item) for item in value]
    if isinstance(value, float) and not math.isfinite(value):
        return None
    return value


def metric_row(method: str, metric: dict[str, Any]) -> dict[str, Any]:
    return {
        "id": method,
        "name": FRIENDLY_NAMES.get(method, method),
        "brier": json_safe(metric.get("brier")),
        "nll": json_safe(metric.get("nll")),
        "ece": json_safe(metric.get("ece")),
        "false_safe_rate_at_08": json_safe(metric.get("false_safe_rate@0.8")),
        "count": json_safe(metric.get("count")),
    }


def relative_path(path: Path) -> str:
    try:
        return path.resolve().relative_to(PROJECT_ROOT.resolve()).as_posix()
    except ValueError:
        return path.as_posix()


def find_latest_neural_report() -> Path | None:
    candidates = sorted(
        (PROJECT_ROOT / "results").glob("p0_neural*/report.json"),
        key=lambda path: path.stat().st_mtime,
    )
    return candidates[-1] if candidates else None


def neural_snapshot(path: Path | None) -> dict[str, Any] | None:
    if path is None:
        return None
    try:
        report = json.loads(path.read_text(encoding="utf-8"))
    except (OSError, json.JSONDecodeError):
        return None
    event = report.get("event_metrics", {})
    compact = {
        "source": relative_path(path),
        "paper_result": bool(report.get("paper_result", False)),
        "protocol": json_safe(report.get("protocol", {})),
        "event": {
            key: json_safe(event.get(key))
            for key in ("brier", "nll", "ece", "false_safe_rate@0.8", "count")
            if key in event
        },
        "event_mean_by_radius": json_safe(report.get("event_mean_by_radius", [])),
        "target_event_mean_by_radius": json_safe(report.get("target_event_mean_by_radius", [])),
        "map_marginal": json_safe(report.get("map_marginal_metrics", {})),
        "last_training": json_safe(report.get("last_training", {})),
        "interpretation": report.get("interpretation", ""),
    }
    return compact


def cuda_smoke_was_recorded() -> bool:
    verification = PROJECT_ROOT / "results" / "verification.md"
    if not verification.exists():
        return False
    text = verification.read_text(encoding="utf-8", errors="replace").lower()
    return "gpu smoke" in text and ("passed" in text or "pass" in text)


def build_snapshot(report_path: Path) -> dict[str, Any]:
    report = json.loads(report_path.read_text(encoding="utf-8"))
    event_metrics = report.get("event_metrics", {})
    death_test = report.get("death_test", {})
    neural = neural_snapshot(find_latest_neural_report())
    report_time = datetime.fromtimestamp(report_path.stat().st_mtime, timezone.utc).isoformat()

    rows = [metric_row(method, metric) for method, metric in event_metrics.items()]
    pathrel = event_metrics.get("PathRel_correlated_event", {})
    independent = event_metrics.get("independent_bernoulli", {})
    direct = event_metrics.get("direct_query_mlp", {})

    return json_safe(
        {
            "schema_version": 1,
            "project": "ConPath",
            "title": "Connectivity-Calibrated Path Reliability",
            "generated_from": relative_path(report_path),
            "report_mtime_utc": report_time,
            "protocol": report.get("protocol", {}),
            "event_metrics": rows,
            "headline": {
                "oracle_proxy": metric_row("PathRel_correlated_event", pathrel),
                "independent_cells": metric_row("independent_bernoulli", independent),
                "direct_query": metric_row("direct_query_mlp", direct),
                "death_test": report.get("death_test", {}),
            },
            "neural_latest": neural,
            "data_gates": {
                "oracle_proxy": {
                    "label": "PASS",
                    "kind": "pass",
                    "detail": "Correlated posterior proxy beats independent cells and direct q on the synthetic P0 audit.",
                },
                "cuda_smoke": {
                    "label": "PASS",
                    "kind": "pass",
                    "detail": "RTX PRO 6000 environment, forward/backward, and one-step CUDA smoke are recorded.",
                    "recorded": cuda_smoke_was_recorded(),
                },
                "neural_p0": {
                    "label": "ACTIVE",
                    "kind": "warn",
                    "detail": "The latest neural run is diagnostic and is not a paper result until it passes the same gate.",
                    "paper_result": bool(neural and neural.get("paper_result", False)),
                },
                "public_data": {
                    "label": "NO-GO",
                    "kind": "hold",
                    "detail": "FlatLands/real-data loaders are not present in this transfer package.",
                },
            },
            "plots": {
                "comparison": "assets/comparison.svg",
                "reliability": "assets/reliability.svg",
                "metrics_csv": "data/p0_metrics.csv",
            },
            "video": {
                "src": "assets/conpath_p0_demo.mp4",
                "poster": "assets/conpath_p0_demo_poster.png",
                "caption": "Synthetic P0 audit walkthrough; oracle proxy, not a trained neural result.",
            },
        }
    )


def copy_if_present(source: Path, destination: Path) -> bool:
    if not source.exists():
        return False
    destination.parent.mkdir(parents=True, exist_ok=True)
    shutil.copyfile(source, destination)
    return True


def build_real_snapshot(report_path: Path, output_dir: Path) -> list[str]:
    """Copy the compact real-data pilot snapshot used by the public project page.

    The old P0 builder remains available for development audits, but the public page must never
    silently fall back to synthetic figures when a real report is missing.
    """

    report = json.loads(report_path.read_text(encoding="utf-8"))
    assets_dir = output_dir / "assets"
    data_dir = output_dir / "data"
    assets_dir.mkdir(parents=True, exist_ok=True)
    data_dir.mkdir(parents=True, exist_ok=True)
    compact = {
        "schema_version": int(report.get("schema_version", 1)),
        "project": "ConPath",
        "dataset": json_safe(report.get("dataset", {})),
        "protocol": json_safe(report.get("protocol", {})),
        "map": json_safe(report.get("map", {})),
        "metrics": json_safe(report.get("metrics", [])),
        "claim_boundary": report.get("claim_boundary", ""),
        "generated_at_utc": report.get("generated_at_utc"),
        "assets": {
            "teaser": "assets/tum_freiburg1_desk_teaser.jpg",
            "rgb": "assets/tum_freiburg1_desk_rgb.jpg",
            "depth": "assets/tum_freiburg1_desk_depth.jpg",
            "video": "assets/tum_freiburg1_desk_demo.mp4",
            "poster": "assets/tum_freiburg1_desk_demo_poster.jpg",
            "comparison": "assets/tum_freiburg1_desk_comparison.svg",
            "reliability": "assets/tum_freiburg1_desk_reliability.svg",
        },
    }
    snapshot_path = data_dir / "tum_rgbd_pilot.json"
    snapshot_path.write_text(json.dumps(compact, ensure_ascii=False, indent=2, allow_nan=False) + "\n", encoding="utf-8")
    (data_dir / "tum_rgbd_pilot.js").write_text("window.CONPATH_REAL_PILOT = " + json.dumps(compact, ensure_ascii=False, indent=2, allow_nan=False) + ";\n", encoding="utf-8")
    copied: list[str] = []
    for name in ("tum_freiburg1_desk_teaser.jpg", "tum_freiburg1_desk_rgb.jpg", "tum_freiburg1_desk_depth.jpg", "tum_freiburg1_desk_demo.mp4", "tum_freiburg1_desk_demo_poster.jpg", "tum_freiburg1_desk_comparison.svg", "tum_freiburg1_desk_reliability.svg"):
        if copy_if_present(report_path.parent / name, assets_dir / name):
            copied.append(f"assets/{name}")
    return copied


def build_flatlands_snapshot(
    report_path: Path, provenance_report_path: Path
) -> dict[str, Any]:
    """Build a compact, explicitly non-model FlatLands audit snapshot."""

    report = json.loads(report_path.read_text(encoding="utf-8"))
    provenance = json.loads(provenance_report_path.read_text(encoding="utf-8"))
    gates = report.get("gates", {})
    by_split = report.get("query_summary_by_split", {})
    balance = gates.get("query_balance_by_gated_stratum", {})

    totals = {
        "candidate_queries": 0,
        "selected_queries": 0,
        "target_invalid_endpoints": 0,
        "retained_valid_endpoint_queries": 0,
        "disconnected_radius_zero": 0,
        "footprint_failure": 0,
        "high_clearance_positive": 0,
    }
    split_rows: list[dict[str, Any]] = []
    for split_name in ("train", "validation", "test"):
        row = by_split.get(split_name, {})
        statuses = row.get("target_status_counts", {})
        compact_row = {
            "split": split_name,
            "candidate_queries": int(row.get("candidate_queries", 0)),
            "selected_queries": int(row.get("selected_queries", 0)),
            "target_invalid_endpoints": int(row.get("target_invalid_endpoints", 0)),
            "retained_valid_endpoint_queries": int(
                row.get("retained_valid_endpoint_queries", 0)
            ),
            "disconnected_radius_zero": int(
                statuses.get("disconnected_radius_zero", 0)
            ),
            "footprint_failure": int(statuses.get("footprint_failure", 0)),
            "high_clearance_positive": int(
                statuses.get("high_clearance_positive", 0)
            ),
            "reachable_by_radius_cells": json_safe(
                row.get("reachable_by_radius_cells", {})
            ),
            "scene_weighted_failure_rate": json_safe(
                row.get("scene_weighted_failure_rate")
            ),
        }
        split_rows.append(compact_row)
        for key in totals:
            totals[key] += compact_row[key]

    strata: list[dict[str, Any]] = []
    for key, row in report.get("query_summary_by_split_source", {}).items():
        split_name, source = key.split("/", 1)
        if split_name not in {"validation", "test"}:
            continue
        gate = balance.get(key, {})
        strata.append(
            {
                "split": split_name,
                "source": source,
                "retained_queries": int(
                    row.get("retained_valid_endpoint_queries", 0)
                ),
                "retained_scenes": int(row.get("scene_count_with_retained_queries", 0)),
                "scene_weighted_failure_rate": json_safe(
                    row.get("scene_weighted_failure_rate")
                ),
                "reachable_by_radius_cells": json_safe(
                    row.get("reachable_by_radius_cells", {})
                ),
                "gate_passed": bool(gate.get("passed", False)),
            }
        )
    strata.sort(key=lambda item: (item["split"], item["source"]))

    official_overlap = provenance.get("metadata", {}).get("scene_overlap", {})
    provenance_overlap = provenance.get("metadata", {}).get(
        "provenance_scene_overlap", {}
    )
    overlap_rows = []
    for pair in ("train__validation", "train__test", "validation__test"):
        overlap_rows.append(
            {
                "pair": pair.replace("__", " / "),
                "official_scene_overlap": int(official_overlap.get(pair, {}).get("count", 0)),
                "provenance_scene_overlap": int(
                    provenance_overlap.get(pair, {}).get("count", 0)
                ),
            }
        )

    outputs = report.get("outputs", {})
    output_hashes = {
        name: {
            "rows": int(value.get("rows", 0)),
            "sha256": value.get("sha256", ""),
        }
        for name, value in outputs.items()
    }
    passed_strata = sum(bool(row.get("passed", False)) for row in balance.values())
    protocol = report.get("protocol", {})
    return json_safe(
        {
            "schema_version": 1,
            "project": "ConPath",
            "dataset": "FlatLands",
            "kind": "bounded_data_audit",
            "paper_result": False,
            "model_result": False,
            "generated_from": relative_path(report_path),
            "provenance_generated_from": relative_path(provenance_report_path),
            "report_mtime_utc": datetime.fromtimestamp(
                report_path.stat().st_mtime, timezone.utc
            ).isoformat(),
            "data_gate_passed": bool(gates.get("p1_bounded_query_gate_passed", False)),
            "mask_semantics_passed": bool(gates.get("mask_semantics_passed", False)),
            "selected_observations": int(
                report.get("sample", {}).get("selected_observations", 0)
            ),
            "split_source_strata": int(
                report.get("sample", {}).get("split_source_strata", 0)
            ),
            "gated_strata": {
                "passed": passed_strata,
                "total": len(balance),
            },
            "radii_cells": json_safe(protocol.get("footprint_radii_cells", [])),
            "radii_m": json_safe(protocol.get("footprint_radii_m", [])),
            "totals": totals,
            "splits": split_rows,
            "strata": strata,
            "official_split_overlap": overlap_rows,
            "frozen_outputs": output_hashes,
            "adapter": {
                "implementation": "src/pathrel/flatlands_data.py",
                "direct_zip_streaming": True,
                "split_key": "provenance.original_split",
                "physical_archive_split_used_for_evaluation": False,
                "query_geometry_replayed_from_input_only": True,
            },
            "claim_boundary": (
                "This is a bounded target-blind data audit on a non-official, scene-disjoint "
                "provenance split. It is not a trained-model result and is not evidence that "
                "the leaking official FlatLands split is valid."
            ),
        }
    )


def _heat_color(rate: float) -> str:
    rate = max(0.0, min(1.0, rate))
    start = (242, 247, 249)
    end = (45, 138, 112)
    values = tuple(round(a + (b - a) * rate) for a, b in zip(start, end))
    return "#" + "".join(f"{value:02x}" for value in values)


def build_flatlands_reachability_svg(snapshot: dict[str, Any]) -> str:
    rows = snapshot.get("strata", [])
    radii = [str(value) for value in snapshot.get("radii_cells", [])]
    width = 980
    top = 116
    row_height = 35
    label_width = 238
    cell_width = 230
    height = top + row_height * len(rows) + 62
    parts = [
        f'<svg xmlns="http://www.w3.org/2000/svg" width="{width}" height="{height}" viewBox="0 0 {width} {height}">',
        '<rect width="100%" height="100%" fill="#ffffff"/>',
        '<style>text{font-family:Inter,Arial,sans-serif;fill:#263744}.title{font-size:21px;font-weight:700}.sub{font-size:12px;fill:#66737e}.label{font-size:12px}.value{font-size:12px;font-weight:700}</style>',
        '<text class="title" x="24" y="34">FlatLands bounded audit: reachable-event prevalence</text>',
        '<text class="sub" x="24" y="57">Validation/test provenance strata · exact target labels · data audit, not model predictions</text>',
    ]
    for column, radius in enumerate(radii):
        x = label_width + column * cell_width
        parts.append(
            f'<text class="label" x="{x + cell_width / 2:.0f}" y="94" text-anchor="middle">radius {escape(radius)} cells</text>'
        )
    for index, row in enumerate(rows):
        y = top + index * row_height
        label = f'{row["split"]} · {row["source"]}'
        parts.append(
            f'<text class="label" x="24" y="{y + 23}" fill="#53616c">{escape(label)}</text>'
        )
        reachability = row.get("reachable_by_radius_cells", {})
        for column, radius in enumerate(radii):
            item = reachability.get(radius, {})
            rate = float(item.get("rate", 0.0))
            x = label_width + column * cell_width
            text_fill = "#ffffff" if rate >= 0.58 else "#263744"
            parts.extend(
                [
                    f'<rect x="{x + 2}" y="{y + 2}" width="{cell_width - 6}" height="{row_height - 5}" rx="5" fill="{_heat_color(rate)}"/>',
                    f'<text class="value" x="{x + cell_width / 2:.0f}" y="{y + 23}" text-anchor="middle" style="fill:{text_fill}">{rate * 100:.1f}%</text>',
                ]
            )
    parts.append(
        f'<text class="sub" x="24" y="{height - 21}">Each cell is reachable / retained valid-endpoint queries in that source stratum.</text>'
    )
    parts.append("</svg>\n")
    return "".join(parts)


def build_flatlands_outcomes_svg(snapshot: dict[str, Any]) -> str:
    rows = snapshot.get("splits", [])
    categories = (
        ("target_invalid_endpoints", "Target-invalid endpoint", "#d7dde2"),
        ("disconnected_radius_zero", "Disconnected at r=0", "#315b86"),
        ("footprint_failure", "Footprint failure", "#c47b38"),
        ("high_clearance_positive", "Reachable at r=20", "#2d8a70"),
    )
    width, height = 980, 360
    chart_x, chart_width = 185, 750
    bar_height = 48
    parts = [
        f'<svg xmlns="http://www.w3.org/2000/svg" width="{width}" height="{height}" viewBox="0 0 {width} {height}">',
        '<rect width="100%" height="100%" fill="#ffffff"/>',
        '<style>text{font-family:Inter,Arial,sans-serif;fill:#263744}.title{font-size:21px;font-weight:700}.sub{font-size:12px;fill:#66737e}.label{font-size:12px}.total{font-size:11px;fill:#66737e}</style>',
        '<text class="title" x="24" y="34">Selected-query target outcomes</text>',
        '<text class="sub" x="24" y="57">Four mutually exclusive outcomes among target-blind selected queries</text>',
    ]
    legend_x = 24
    for _, label, color in categories:
        parts.append(f'<rect x="{legend_x}" y="76" width="12" height="12" rx="2" fill="{color}"/>')
        parts.append(f'<text class="label" x="{legend_x + 18}" y="87">{escape(label)}</text>')
        legend_x += 226
    for index, row in enumerate(rows):
        y = 126 + index * 72
        total = max(1, int(row.get("selected_queries", 0)))
        parts.append(
            f'<text class="label" x="24" y="{y + 29}" font-weight="700">{escape(str(row.get("split", "")))}</text>'
        )
        x = chart_x
        for key, _, color in categories:
            count = int(row.get(key, 0))
            segment = chart_width * count / total
            parts.append(
                f'<rect x="{x:.2f}" y="{y}" width="{segment:.2f}" height="{bar_height}" fill="{color}"/>'
            )
            if segment >= 56:
                text_color = "#263744" if key == "target_invalid_endpoints" else "#ffffff"
                parts.append(
                    f'<text x="{x + segment / 2:.2f}" y="{y + 29}" text-anchor="middle" font-size="11" font-weight="700" style="fill:{text_color}">{count}</text>'
                )
            x += segment
        parts.append(
            f'<text class="total" x="{chart_x + chart_width}" y="{y + 63}" text-anchor="end">n = {total:,} selected</text>'
        )
    parts.append("</svg>\n")
    return "".join(parts)


def build_flatlands_site(
    report_path: Path, provenance_report_path: Path, output_dir: Path
) -> dict[str, Any]:
    snapshot = build_flatlands_snapshot(report_path, provenance_report_path)
    data_dir = output_dir / "data"
    assets_dir = output_dir / "assets"
    data_dir.mkdir(parents=True, exist_ok=True)
    assets_dir.mkdir(parents=True, exist_ok=True)
    payload = json.dumps(snapshot, ensure_ascii=False, indent=2, allow_nan=False)
    (data_dir / "flatlands_audit.json").write_text(payload + "\n", encoding="utf-8")
    (data_dir / "flatlands_audit.js").write_text(
        "window.CONPATH_FLATLANDS_AUDIT = " + payload + ";\n", encoding="utf-8"
    )
    (assets_dir / "flatlands_reachability.svg").write_text(
        build_flatlands_reachability_svg(snapshot), encoding="utf-8"
    )
    (assets_dir / "flatlands_query_outcomes.svg").write_text(
        build_flatlands_outcomes_svg(snapshot), encoding="utf-8"
    )
    return snapshot


BASELINE_FRIENDLY_NAMES = {
    "radius_prior_control": "Radius-prior control",
    "deterministic_completion": "Deterministic completion",
    "independent_cell_completion_k32": "Independent-cell completion (K=32)",
    "direct_query": "Direct-query predictor",
}


def _baseline_metric_item(report: dict[str, Any], scope: str, radius: int | None = None) -> dict[str, Any] | None:
    for item in report.get("metrics", []):
        if item.get("scope") != scope:
            continue
        if radius is None and item.get("radius_cells") is not None:
            continue
        if radius is not None and item.get("radius_cells") != radius:
            continue
        return item
    return None


def _compact_baseline_metric(item: dict[str, Any], *, include_reliability: bool = False) -> dict[str, Any]:
    output: dict[str, Any] = {
        "scope": item.get("scope"),
        "source_dataset": item.get("source_dataset"),
        "radius_cells": item.get("radius_cells"),
    }
    for weighting in ("scene_weighted", "query_weighted"):
        metric = item.get(weighting, {})
        output[weighting] = {
            key: json_safe(metric.get(key))
            for key in (
                "brier",
                "nll",
                "ece",
                "false_safe_rate@0.8",
                "high_confidence_safe_coverage@0.8",
                "positive_rate",
                "mean_probability",
                "count",
                "scene_count",
            )
            if key in metric
        }
        if include_reliability:
            output[weighting]["reliability"] = json_safe(metric.get("reliability", []))
    output["scene_bootstrap_95"] = json_safe(item.get("scene_bootstrap_95", {}))
    return output


def build_flatlands_baseline_snapshot(
    report_paths: dict[str, Path],
) -> dict[str, Any]:
    """Compact the validation-only baseline reports without promoting them to paper results."""

    methods: list[dict[str, Any]] = []
    radii: set[int] = set()
    for method, path in report_paths.items():
        report = json.loads(path.read_text(encoding="utf-8"))
        if report.get("paper_result", True):
            raise ValueError(f"baseline report must be marked non-paper: {path}")
        overall_item = _baseline_metric_item(report, "overall")
        if overall_item is None:
            raise ValueError(f"baseline report has no overall metric: {path}")
        compact = {
            "id": method,
            "name": BASELINE_FRIENDLY_NAMES.get(method, method),
            "report": relative_path(path),
            "overall": _compact_baseline_metric(overall_item, include_reliability=True),
            "by_radius": [],
            "by_source": [],
            "radius_monotonicity": json_safe(report.get("radius_monotonicity", {})),
        }
        for item in report.get("metrics", []):
            scope = item.get("scope")
            if scope == "radius":
                radius = int(item["radius_cells"])
                radii.add(radius)
                compact["by_radius"].append(_compact_baseline_metric(item))
            elif scope == "source":
                compact["by_source"].append(_compact_baseline_metric(item))
        compact["by_radius"].sort(key=lambda item: item["radius_cells"])
        compact["by_source"].sort(key=lambda item: str(item["source_dataset"]))
        methods.append(compact)
    methods.sort(key=lambda item: list(report_paths).index(item["id"]))
    return json_safe(
        {
            "schema_version": 1,
            "project": "ConPath",
            "dataset": "FlatLands",
            "kind": "validation_baseline_snapshot",
            "paper_result": False,
            "test_evaluated": False,
            "protocol": "P1_BASELINE_PROTOCOL.md v1",
            "primary_weighting": "equal source-scene, then equal event within scene",
            "radii_cells": sorted(radii),
            "methods": methods,
            "claim_boundary": (
                "Validation-only baseline diagnostics on the bounded provenance split. The test "
                "split is still locked, and these numbers are not final paper results."
            ),
        }
    )


def build_flatlands_baseline_comparison_svg(snapshot: dict[str, Any]) -> str:
    methods = snapshot.get("methods", [])
    colors = {"radius_prior_control": "#8c99a8", "deterministic_completion": "#315b86", "independent_cell_completion_k32": "#c47b38", "direct_query": "#2d8a70"}
    metrics = (("brier", "Brier ↓"), ("nll", "NLL ↓"), ("ece", "ECE ↓"))
    width, height = 1120, 590
    panel_left, panel_top, panel_width, panel_height, gap = 72, 116, 290, 340, 48
    parts = [
        f'<svg xmlns="http://www.w3.org/2000/svg" width="{width}" height="{height}" viewBox="0 0 {width} {height}">',
        '<rect width="100%" height="100%" fill="#ffffff"/>',
        '<style>text{font-family:Inter,Arial,sans-serif;fill:#263744}.title{font-size:21px;font-weight:700}.sub{font-size:12px;fill:#66737e}.axis{stroke:#aeb8c0}.label{font-size:11px}.value{font-size:11px;font-weight:700}</style>',
        '<text class="title" x="24" y="34">FlatLands validation baselines</text>',
        '<text class="sub" x="24" y="57">Scene-weighted event metrics · provenance split · validation only · lower is better</text>',
    ]
    for method_index, method in enumerate(methods):
        x = 24 + method_index * 270
        color = colors.get(method["id"], "#53616c")
        parts.append(f'<rect x="{x}" y="78" width="12" height="12" rx="2" fill="{color}"/>')
        parts.append(f'<text class="label" x="{x + 18}" y="89">{escape(method["name"])}</text>')
    for panel_index, (key, label) in enumerate(metrics):
        left = panel_left + panel_index * (panel_width + gap)
        values = [float(method["overall"]["scene_weighted"].get(key, 0.0) or 0.0) for method in methods]
        upper = max(0.05, max(values, default=0.05) * 1.18)
        parts.append(f'<text class="label" x="{left}" y="100">{label}</text>')
        parts.append(f'<line class="axis" x1="{left}" y1="{panel_top + panel_height}" x2="{left + panel_width}" y2="{panel_top + panel_height}"/>')
        bar_width = panel_width / max(1, len(methods)) * 0.64
        for index, (method, value) in enumerate(zip(methods, values)):
            x = left + (index + 0.5) * panel_width / len(methods) - bar_width / 2
            bar_height = panel_height * value / upper
            y = panel_top + panel_height - bar_height
            color = colors.get(method["id"], "#53616c")
            parts.append(f'<rect x="{x:.2f}" y="{y:.2f}" width="{bar_width:.2f}" height="{bar_height:.2f}" rx="4" fill="{color}"/>')
            parts.append(f'<text class="value" x="{x + bar_width / 2:.2f}" y="{max(panel_top + 12, y - 6):.2f}" text-anchor="middle">{value:.3f}</text>')
            parts.append(f'<text class="label" x="{x + bar_width / 2:.2f}" y="{panel_top + panel_height + 22}" text-anchor="middle">{index + 1}</text>')
    parts.append(f'<text class="sub" x="24" y="{height - 23}">Bar order is shown in the legend; full source/radius metrics and bootstrap intervals are in flatlands_baselines_validation.json.</text>')
    parts.append("</svg>\n")
    return "".join(parts)


def build_flatlands_baseline_reliability_svg(snapshot: dict[str, Any]) -> str:
    colors = {"radius_prior_control": "#8c99a8", "deterministic_completion": "#315b86", "independent_cell_completion_k32": "#c47b38", "direct_query": "#2d8a70"}
    left, top, plot_width, plot_height = 86, 84, 470, 370
    width, height = 1120, 520
    parts = [
        f'<svg xmlns="http://www.w3.org/2000/svg" width="{width}" height="{height}" viewBox="0 0 {width} {height}">',
        '<rect width="100%" height="100%" fill="#ffffff"/>',
        '<style>text{font-family:Inter,Arial,sans-serif;fill:#263744}.title{font-size:21px;font-weight:700}.sub{font-size:12px;fill:#66737e}.grid{stroke:#e4e9ed}.axis{stroke:#aeb8c0}.legend{font-size:12px}</style>',
        '<text class="title" x="24" y="34">FlatLands validation reliability</text>',
        '<text class="sub" x="24" y="57">Overall scene-weighted calibration bins · validation only</text>',
    ]
    for tick in range(6):
        value = tick / 5
        x = left + value * plot_width
        y = top + plot_height - value * plot_height
        parts.append(f'<line class="grid" x1="{x:.1f}" y1="{top}" x2="{x:.1f}" y2="{top + plot_height}"/>')
        parts.append(f'<line class="grid" x1="{left}" y1="{y:.1f}" x2="{left + plot_width}" y2="{y:.1f}"/>')
        parts.append(f'<text x="{x - 6:.1f}" y="{top + plot_height + 20}">{value:.1f}</text>')
        parts.append(f'<text x="{left - 28}" y="{y + 4:.1f}">{value:.1f}</text>')
    parts.extend(
        [
            f'<line class="axis" x1="{left}" y1="{top + plot_height}" x2="{left + plot_width}" y2="{top}" stroke-dasharray="5,5"/>',
            f'<line class="axis" x1="{left}" y1="{top + plot_height}" x2="{left + plot_width}" y2="{top + plot_height}"/>',
            f'<line class="axis" x1="{left}" y1="{top}" x2="{left}" y2="{top + plot_height}"/>',
            f'<text class="sub" x="{left + plot_width / 2 - 54}" y="{top + plot_height + 44}">mean predicted probability</text>',
            f'<text class="sub" transform="translate(20 {top + plot_height / 2 + 70}) rotate(-90)">empirical event frequency</text>',
        ]
    )
    for method_index, method in enumerate(snapshot.get("methods", [])):
        metric = method["overall"]["scene_weighted"]
        points = []
        for item in metric.get("reliability", []):
            if item.get("weight", 0.0):
                x = left + float(item["confidence"]) * plot_width
                y = top + plot_height - float(item["accuracy"]) * plot_height
                points.append(f"{x:.1f},{y:.1f}")
        color = colors.get(method["id"], "#53616c")
        if points:
            parts.append(f'<polyline points="{" ".join(points)}" fill="none" stroke="{color}" stroke-width="3"/>')
        legend_y = top + 20 + method_index * 25
        parts.append(f'<line x1="650" y1="{legend_y - 5}" x2="678" y2="{legend_y - 5}" stroke="{color}" stroke-width="3"/>')
        parts.append(f'<text class="legend" x="688" y="{legend_y}">{escape(method["name"])} (Brier {float(metric["brier"]):.3f})</text>')
    parts.extend(
        [
            '<text x="650" y="250" font-size="16">Reading the plot</text>',
            '<text class="sub" x="650" y="276">The dashed diagonal is perfect calibration.</text>',
            '<text class="sub" x="650" y="298">Points below it are over-confident / false-safe.</text>',
            '</svg>\n',
        ]
    )
    return "".join(parts)


def build_flatlands_baseline_site(
    report_paths: dict[str, Path], output_dir: Path
) -> dict[str, Any]:
    snapshot = build_flatlands_baseline_snapshot(report_paths)
    data_dir = output_dir / "data"
    assets_dir = output_dir / "assets"
    data_dir.mkdir(parents=True, exist_ok=True)
    assets_dir.mkdir(parents=True, exist_ok=True)
    payload = json.dumps(snapshot, ensure_ascii=False, indent=2, allow_nan=False)
    (data_dir / "flatlands_baselines_validation.json").write_text(payload + "\n", encoding="utf-8")
    (data_dir / "flatlands_baselines_validation.js").write_text(
        "window.CONPATH_FLATLANDS_BASELINES = " + payload + ";\n", encoding="utf-8"
    )
    (assets_dir / "flatlands_baseline_comparison.svg").write_text(
        build_flatlands_baseline_comparison_svg(snapshot), encoding="utf-8"
    )
    (assets_dir / "flatlands_baseline_reliability.svg").write_text(
        build_flatlands_baseline_reliability_svg(snapshot), encoding="utf-8"
    )
    return snapshot


def main() -> None:
    args = parse_args()
    report_path = args.report.resolve()
    output_dir = args.output_dir.resolve()
    real_report = args.real_report.resolve()
    flatlands_report = args.flatlands_report.resolve()
    flatlands_provenance_report = args.flatlands_provenance_report.resolve()
    flatlands_baseline_root = args.flatlands_baseline_root.resolve()
    if not args.skip_real and not real_report.exists():
        raise SystemExit(
            f"Real-data pilot report not found: {real_report}\n"
            "Run /usr/bin/python3 scripts/run_tum_rgbd_pilot.py --publish-site first, "
            "or pass --skip-real for the legacy synthetic audit."
        )

    (output_dir / "data").mkdir(parents=True, exist_ok=True)
    (output_dir / "assets").mkdir(parents=True, exist_ok=True)
    if report_path.exists() and (args.include_legacy or args.skip_real):
        snapshot = build_snapshot(report_path)
        snapshot_path = output_dir / "data" / "p0_metrics.json"
        snapshot_path.write_text(
            json.dumps(snapshot, ensure_ascii=False, indent=2, allow_nan=False) + "\n",
            encoding="utf-8",
        )
        # The JS mirror keeps the legacy audit usable when someone opens index.html directly from
        # disk. The public page itself consumes only tum_rgbd_pilot.js.
        (output_dir / "data" / "p0_metrics.js").write_text(
            "window.CONPATH_SNAPSHOT = "
            + json.dumps(snapshot, ensure_ascii=False, indent=2, allow_nan=False)
            + ";\n",
            encoding="utf-8",
        )
        copied = []
        for source_name, destination_name in (("comparison.svg", "comparison.svg"), ("reliability.svg", "reliability.svg")):
            if copy_if_present(report_path.parent / source_name, output_dir / "assets" / destination_name):
                copied.append(destination_name)
        csv_source = report_path.parent / "metrics.csv"
        if copy_if_present(csv_source, output_dir / "data" / "p0_metrics.csv"):
            copied.append("data/p0_metrics.csv")
        print(f"Wrote legacy P0 snapshot: {snapshot_path}")
        if copied:
            print("Copied " + ", ".join(copied))
    elif args.skip_real:
        raise SystemExit(f"P0 report not found: {report_path}\nRun scripts/evaluate_p0.py first.")
    else:
        print("No legacy synthetic P0 report found; building the real-data page only.")
    if not args.skip_real:
        real_copied = build_real_snapshot(real_report, output_dir)
        print(f"Built primary real-data snapshot from {relative_path(real_report)}")
        if real_copied:
            print("Copied " + ", ".join(real_copied))
    if not args.skip_flatlands:
        missing = [
            path
            for path in (flatlands_report, flatlands_provenance_report)
            if not path.exists()
        ]
        if missing:
            raise SystemExit(
                "FlatLands audit report(s) not found: "
                + ", ".join(str(path) for path in missing)
                + "\nRun the bounded provenance/query audits first, or pass --skip-flatlands."
            )
        snapshot = build_flatlands_site(
            flatlands_report, flatlands_provenance_report, output_dir
        )
        print(
            "Built FlatLands bounded data-audit snapshot: "
            f'{snapshot["selected_observations"]} observations, '
            f'{snapshot["totals"]["retained_valid_endpoint_queries"]} retained queries'
        )
        if not args.skip_flatlands_baselines:
            baseline_paths = {
                "radius_prior_control": flatlands_baseline_root
                / "p1_flatlands_radius_prior_validation"
                / "evaluation"
                / "report.json",
                "deterministic_completion": flatlands_baseline_root
                / "p1_flatlands_completion_seed20260831"
                / "evaluation_deterministic_validation"
                / "report.json",
                "independent_cell_completion_k32": flatlands_baseline_root
                / "p1_flatlands_completion_seed20260831"
                / "evaluation_independent_k32_validation"
                / "report.json",
                "direct_query": flatlands_baseline_root
                / "p1_flatlands_direct_query_seed20260831"
                / "evaluation_validation"
                / "report.json",
            }
            baseline_missing = [path for path in baseline_paths.values() if not path.exists()]
            if baseline_missing:
                print(
                    "Skipped FlatLands validation baseline snapshot; missing report(s): "
                    + ", ".join(str(path) for path in baseline_missing)
                )
            else:
                baseline_snapshot = build_flatlands_baseline_site(baseline_paths, output_dir)
                print(
                    "Built FlatLands validation baseline snapshot: "
                    f'{len(baseline_snapshot["methods"])} methods, '
                    f'{len(baseline_snapshot["radii_cells"])} radii'
                )


if __name__ == "__main__":
    main()
