#!/usr/bin/env python3
"""Build the tracked, static ConPath research demo from an experiment report.

The website intentionally consumes a compact snapshot rather than loading files from ``results/``
at runtime.  ``results/`` is ignored because it contains large/reproducible experiment outputs;
the small snapshot under ``site/data`` is the reviewable hand-off that travels with the repository.
"""

from __future__ import annotations

import argparse
from datetime import datetime, timezone
import json
import math
from pathlib import Path
import shutil
from typing import Any


PROJECT_ROOT = Path(__file__).resolve().parents[1]
DEFAULT_REAL_REPORT = PROJECT_ROOT / "results" / "tum_rgbd_freiburg1_desk_pilot" / "report.json"

FRIENDLY_NAMES = {
    "constant_query_radius": "Constant query-radius prior",
    "independent_bernoulli": "Independent cell completion",
    "direct_query_mlp": "Direct query predictor",
    "edge_connectivity_calibrated": "Edge-connectivity calibrated",
    "random_completion": "Uniform unknown completion",
    "deterministic_threshold": "Deterministic threshold",
    "correlated_decoder_no_reachability": "Correlated decoder (no reachability)",
    "PathRel_correlated_event": "ConPath correlated event (oracle proxy)",
}


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument(
        "--report",
        type=Path,
        default=PROJECT_ROOT / "results" / "p0_death_test" / "report.json",
        help="P0 report generated by scripts/evaluate_p0.py",
    )
    parser.add_argument(
        "--output-dir",
        type=Path,
        default=PROJECT_ROOT / "site",
        help="tracked static site directory",
    )
    parser.add_argument(
        "--real-report",
        type=Path,
        default=DEFAULT_REAL_REPORT,
        help="real-data pilot report generated by scripts/run_tum_rgbd_pilot.py",
    )
    parser.add_argument(
        "--skip-real",
        action="store_true",
        help="only rebuild the legacy synthetic P0 snapshot (development use)",
    )
    parser.add_argument(
        "--include-legacy",
        action="store_true",
        help="also copy legacy synthetic P0 assets (never used by the public page)",
    )
    return parser.parse_args()


def json_safe(value: Any) -> Any:
    """Convert NumPy-style non-finite values into strict JSON ``null`` values."""

    if isinstance(value, dict):
        return {str(key): json_safe(item) for key, item in value.items()}
    if isinstance(value, (list, tuple)):
        return [json_safe(item) for item in value]
    if isinstance(value, float) and not math.isfinite(value):
        return None
    return value


def metric_row(method: str, metric: dict[str, Any]) -> dict[str, Any]:
    return {
        "id": method,
        "name": FRIENDLY_NAMES.get(method, method),
        "brier": json_safe(metric.get("brier")),
        "nll": json_safe(metric.get("nll")),
        "ece": json_safe(metric.get("ece")),
        "false_safe_rate_at_08": json_safe(metric.get("false_safe_rate@0.8")),
        "count": json_safe(metric.get("count")),
    }


def relative_path(path: Path) -> str:
    try:
        return path.resolve().relative_to(PROJECT_ROOT.resolve()).as_posix()
    except ValueError:
        return path.as_posix()


def find_latest_neural_report() -> Path | None:
    candidates = sorted(
        (PROJECT_ROOT / "results").glob("p0_neural*/report.json"),
        key=lambda path: path.stat().st_mtime,
    )
    return candidates[-1] if candidates else None


def neural_snapshot(path: Path | None) -> dict[str, Any] | None:
    if path is None:
        return None
    try:
        report = json.loads(path.read_text(encoding="utf-8"))
    except (OSError, json.JSONDecodeError):
        return None
    event = report.get("event_metrics", {})
    compact = {
        "source": relative_path(path),
        "paper_result": bool(report.get("paper_result", False)),
        "protocol": json_safe(report.get("protocol", {})),
        "event": {
            key: json_safe(event.get(key))
            for key in ("brier", "nll", "ece", "false_safe_rate@0.8", "count")
            if key in event
        },
        "event_mean_by_radius": json_safe(report.get("event_mean_by_radius", [])),
        "target_event_mean_by_radius": json_safe(report.get("target_event_mean_by_radius", [])),
        "map_marginal": json_safe(report.get("map_marginal_metrics", {})),
        "last_training": json_safe(report.get("last_training", {})),
        "interpretation": report.get("interpretation", ""),
    }
    return compact


def cuda_smoke_was_recorded() -> bool:
    verification = PROJECT_ROOT / "results" / "verification.md"
    if not verification.exists():
        return False
    text = verification.read_text(encoding="utf-8", errors="replace").lower()
    return "gpu smoke" in text and ("passed" in text or "pass" in text)


def build_snapshot(report_path: Path) -> dict[str, Any]:
    report = json.loads(report_path.read_text(encoding="utf-8"))
    event_metrics = report.get("event_metrics", {})
    death_test = report.get("death_test", {})
    neural = neural_snapshot(find_latest_neural_report())
    report_time = datetime.fromtimestamp(report_path.stat().st_mtime, timezone.utc).isoformat()

    rows = [metric_row(method, metric) for method, metric in event_metrics.items()]
    pathrel = event_metrics.get("PathRel_correlated_event", {})
    independent = event_metrics.get("independent_bernoulli", {})
    direct = event_metrics.get("direct_query_mlp", {})

    return json_safe(
        {
            "schema_version": 1,
            "project": "ConPath",
            "title": "Connectivity-Calibrated Path Reliability",
            "generated_from": relative_path(report_path),
            "report_mtime_utc": report_time,
            "protocol": report.get("protocol", {}),
            "event_metrics": rows,
            "headline": {
                "oracle_proxy": metric_row("PathRel_correlated_event", pathrel),
                "independent_cells": metric_row("independent_bernoulli", independent),
                "direct_query": metric_row("direct_query_mlp", direct),
                "death_test": report.get("death_test", {}),
            },
            "neural_latest": neural,
            "data_gates": {
                "oracle_proxy": {
                    "label": "PASS",
                    "kind": "pass",
                    "detail": "Correlated posterior proxy beats independent cells and direct q on the synthetic P0 audit.",
                },
                "cuda_smoke": {
                    "label": "PASS",
                    "kind": "pass",
                    "detail": "RTX PRO 6000 environment, forward/backward, and one-step CUDA smoke are recorded.",
                    "recorded": cuda_smoke_was_recorded(),
                },
                "neural_p0": {
                    "label": "ACTIVE",
                    "kind": "warn",
                    "detail": "The latest neural run is diagnostic and is not a paper result until it passes the same gate.",
                    "paper_result": bool(neural and neural.get("paper_result", False)),
                },
                "public_data": {
                    "label": "NO-GO",
                    "kind": "hold",
                    "detail": "FlatLands/real-data loaders are not present in this transfer package.",
                },
            },
            "plots": {
                "comparison": "assets/comparison.svg",
                "reliability": "assets/reliability.svg",
                "metrics_csv": "data/p0_metrics.csv",
            },
            "video": {
                "src": "assets/conpath_p0_demo.mp4",
                "poster": "assets/conpath_p0_demo_poster.png",
                "caption": "Synthetic P0 audit walkthrough; oracle proxy, not a trained neural result.",
            },
        }
    )


def copy_if_present(source: Path, destination: Path) -> bool:
    if not source.exists():
        return False
    destination.parent.mkdir(parents=True, exist_ok=True)
    shutil.copyfile(source, destination)
    return True


def build_real_snapshot(report_path: Path, output_dir: Path) -> list[str]:
    """Copy the compact real-data pilot snapshot used by the public project page.

    The old P0 builder remains available for development audits, but the public page must never
    silently fall back to synthetic figures when a real report is missing.
    """

    report = json.loads(report_path.read_text(encoding="utf-8"))
    assets_dir = output_dir / "assets"
    data_dir = output_dir / "data"
    assets_dir.mkdir(parents=True, exist_ok=True)
    data_dir.mkdir(parents=True, exist_ok=True)
    compact = {
        "schema_version": int(report.get("schema_version", 1)),
        "project": "ConPath",
        "dataset": json_safe(report.get("dataset", {})),
        "protocol": json_safe(report.get("protocol", {})),
        "map": json_safe(report.get("map", {})),
        "metrics": json_safe(report.get("metrics", [])),
        "claim_boundary": report.get("claim_boundary", ""),
        "generated_at_utc": report.get("generated_at_utc"),
        "assets": {
            "teaser": "assets/tum_freiburg1_desk_teaser.jpg",
            "rgb": "assets/tum_freiburg1_desk_rgb.jpg",
            "depth": "assets/tum_freiburg1_desk_depth.jpg",
            "video": "assets/tum_freiburg1_desk_demo.mp4",
            "poster": "assets/tum_freiburg1_desk_demo_poster.jpg",
            "comparison": "assets/tum_freiburg1_desk_comparison.svg",
            "reliability": "assets/tum_freiburg1_desk_reliability.svg",
        },
    }
    snapshot_path = data_dir / "tum_rgbd_pilot.json"
    snapshot_path.write_text(json.dumps(compact, ensure_ascii=False, indent=2, allow_nan=False) + "\n", encoding="utf-8")
    (data_dir / "tum_rgbd_pilot.js").write_text("window.CONPATH_REAL_PILOT = " + json.dumps(compact, ensure_ascii=False, indent=2, allow_nan=False) + ";\n", encoding="utf-8")
    copied: list[str] = []
    for name in ("tum_freiburg1_desk_teaser.jpg", "tum_freiburg1_desk_rgb.jpg", "tum_freiburg1_desk_depth.jpg", "tum_freiburg1_desk_demo.mp4", "tum_freiburg1_desk_demo_poster.jpg", "tum_freiburg1_desk_comparison.svg", "tum_freiburg1_desk_reliability.svg"):
        if copy_if_present(report_path.parent / name, assets_dir / name):
            copied.append(f"assets/{name}")
    return copied


def main() -> None:
    args = parse_args()
    report_path = args.report.resolve()
    output_dir = args.output_dir.resolve()
    real_report = args.real_report.resolve()
    if not args.skip_real and not real_report.exists():
        raise SystemExit(
            f"Real-data pilot report not found: {real_report}\n"
            "Run /usr/bin/python3 scripts/run_tum_rgbd_pilot.py --publish-site first, "
            "or pass --skip-real for the legacy synthetic audit."
        )

    (output_dir / "data").mkdir(parents=True, exist_ok=True)
    (output_dir / "assets").mkdir(parents=True, exist_ok=True)
    if report_path.exists() and (args.include_legacy or args.skip_real):
        snapshot = build_snapshot(report_path)
        snapshot_path = output_dir / "data" / "p0_metrics.json"
        snapshot_path.write_text(
            json.dumps(snapshot, ensure_ascii=False, indent=2, allow_nan=False) + "\n",
            encoding="utf-8",
        )
        # The JS mirror keeps the legacy audit usable when someone opens index.html directly from
        # disk. The public page itself consumes only tum_rgbd_pilot.js.
        (output_dir / "data" / "p0_metrics.js").write_text(
            "window.CONPATH_SNAPSHOT = "
            + json.dumps(snapshot, ensure_ascii=False, indent=2, allow_nan=False)
            + ";\n",
            encoding="utf-8",
        )
        copied = []
        for source_name, destination_name in (("comparison.svg", "comparison.svg"), ("reliability.svg", "reliability.svg")):
            if copy_if_present(report_path.parent / source_name, output_dir / "assets" / destination_name):
                copied.append(destination_name)
        csv_source = report_path.parent / "metrics.csv"
        if copy_if_present(csv_source, output_dir / "data" / "p0_metrics.csv"):
            copied.append("data/p0_metrics.csv")
        print(f"Wrote legacy P0 snapshot: {snapshot_path}")
        if copied:
            print("Copied " + ", ".join(copied))
    elif args.skip_real:
        raise SystemExit(f"P0 report not found: {report_path}\nRun scripts/evaluate_p0.py first.")
    else:
        print("No legacy synthetic P0 report found; building the real-data page only.")
    if not args.skip_real:
        real_copied = build_real_snapshot(real_report, output_dir)
        print(f"Built primary real-data snapshot from {relative_path(real_report)}")
        if real_copied:
            print("Copied " + ", ".join(real_copied))


if __name__ == "__main__":
    main()
